### ISSUE TITLE
How to write the obj files sequence for blender

### ISSUE THREAD

**Issue by HackerSnail** [PeizhuoLi/manifold-aware-transformers#1]
It is a nice work,but the function write_objs is not called. How to load the sequence in blender

**Comment by PeizhuoLi** [comment]
You may refer to [this](https://github.com/PeizhuoLi/manifold-aware-transformers#mesh-sequence-format-and-visualization) section on visualizing the customized pkl file in Blender with the provided plugin. Alternatively, it is also possible to parse the pkl file according to [this](https://github.com/PeizhuoLi/manifold-aware-transformers/blob/e54066c75635538e28ac55fff50a9123f5edc0f2/mesh_utils.py#L360) function and export it as obj files.

**Comment by HackerSnail** [comment]
thank you
